#! /usr/bin/env python

from gcat_runner import __version__
import gcat_runner.runner
import argparse

parser = argparse.ArgumentParser(prog = "gcat_runner")

parser.add_argument("--version", action = "version", version = "gcat_runner-" + __version__)

parser.add_argument('script', metavar = "/path/to/singularity_bwa.sh", type = str, help = "Input singularity script")
parser.add_argument("conf", metavar = "/path/to/sample.conf.yml", type = str, help = "Input sample list flie [YAML]")
parser.add_argument("--interval", metavar = "1", type = int, help = "Maximum waiting time (sec) to submit", default = 3)
parser.add_argument("--without_sync", help = "Do not wait for job to finish", action='store_true')
parser.set_defaults(handler=gcat_runner.runner.main)

args = parser.parse_args()

args.handler(args)
